name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: gh-runner-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          # Add your build and test commands here
          echo "Building and testing..."

